index:
    path: /
    controller: App\Controller\DefaultController::index
    
    
crear-categoria:
    path: /savecategoria
    controller: App\Controller\CategoriaController::createcategoria
    
mis-categorias:
    path: /categorias
    controller: App\Controller\CategoriaController::miscategorias
    
    
crear-producto:
    path: /saveproducto
    controller: App\Controller\ProductoController::createproducto
    
    
mis-productos:
    path: /productos
    controller: App\Controller\ProductoController::misproductos