index:
    path: /
    controller: App\Controller\DefaultController::index
    
    
crear-categoria:
    path: /categoria
    controller: App\Controller\CategoriaController::createcategoria
    
    
crear-producto:
    path: /producto
    controller: App\Controller\CategoriaController::createproducto